# CI always looks for this string: PRX_
version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: "/prx/DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "/prx/DOCKERHUB_PASSWORD"
    DOVETAIL_HOST: "/prx/test/meta.prx.org/DOVETAIL_HOST"
    DOVETAIL_PROD_HOST: "/prx/test/meta.prx.org/DOVETAIL_PROD_HOST"
    FEEDER_HOST: "/prx/test/meta.prx.org/FEEDER_HOST"
    METRICS_HOST: "/prx/test/meta.prx.org/METRICS_HOST"
    PUBLISH_HOST: "/prx/test/meta.prx.org/PUBLISH_HOST"
    PUBLISH_PASS: "/prx/test/meta.prx.org/PUBLISH_PASS"
    PUBLISH_USER: "/prx/test/meta.prx.org/PUBLISH_USER"
    UPLOAD_HOST: "/prx/test/meta.prx.org/UPLOAD_HOST"
    PORTER_STATE_MACHINE_ARN: "/prx/test/meta.prx.org/PORTER_STATE_MACHINE_ARN"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "docker-compose -f docker-compose-ci.yml build"
      - "docker-compose -f docker-compose-ci.yml run meta"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
