version: 0.2
env:
  parameter-store:
    DOVETAIL_HOST: "/prx/test/meta.prx.org/DOVETAIL_HOST"
    DOVETAIL_PROD_HOST: "/prx/test/meta.prx.org/DOVETAIL_PROD_HOST"
    FEEDER_HOST: "/prx/test/meta.prx.org/FEEDER_HOST"
    METRICS_HOST: "/prx/test/meta.prx.org/METRICS_HOST"
    PUBLISH_HOST: "/prx/test/meta.prx.org/PUBLISH_HOST"
    PUBLISH_PASS: "/prx/test/meta.prx.org/PUBLISH_PASS"
    PUBLISH_USER: "/prx/test/meta.prx.org/PUBLISH_USER"
    UPLOAD_HOST: "/prx/test/meta.prx.org/UPLOAD_HOST"
    PORTER_STATE_MACHINE_ARN: "/prx/test/meta.prx.org/PORTER_STATE_MACHINE_ARN"
phases:
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake
artifacts:
  files:
    - README.md
