version: 0.2
env:
  variables:
    DOVETAIL_PROD_HOST: dovetail.prxu.org
  parameter-store:
    PUBLISH_PASS: /prx/test/meta.prx.org/PUBLISH_PASS
    PUBLISH_USER: /prx/test/meta.prx.org/PUBLISH_USER
    # DOVETAIL_HOST: "/prx/test/meta.prx.org/DOVETAIL_HOST"
    # FEEDER_HOST: "/prx/test/meta.prx.org/FEEDER_HOST"
    # METRICS_HOST: "/prx/test/meta.prx.org/METRICS_HOST"
    # PUBLISH_HOST: "/prx/test/meta.prx.org/PUBLISH_HOST"
    # UPLOAD_HOST: "/prx/test/meta.prx.org/UPLOAD_HOST"
    PORTER_STATE_MACHINE_ARN: /prx/test/meta.prx.org/PORTER_STATE_MACHINE_ARN
phases:
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake
artifacts:
  files:
    - README.md
