version: 0.2
env:
  variables:
    DOVETAIL_PROD_HOST: dovetail.prxu.org
  parameter-store:
    PUBLISH_PASS: /prx/test/meta.prx.org/PUBLISH_PASS
    PUBLISH_USER: /prx/test/meta.prx.org/PUBLISH_USER
phases:
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake
artifacts:
  files:
    - README.md
