meta:
  build: .
  volumes:
    - .:/home
  entrypoint: bundle exec rake
  command: test
  environment:
    - AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    - DOVETAIL_HOST
    - DOVETAIL_PROD_HOST
    - FEEDER_HOST
    - METRICS_HOST
    - PUBLISH_HOST
    - PUBLISH_USER
    - PUBLISH_PASS
    - UPLOAD_HOST
    - PORTER_STATE_MACHINE_ARN
