version: '2'
services:
  test:
    build: .
    command: ci
    env_file:
      - .env
    # uncomment to run docker on mac m1
    # platform: linux/amd64
    volumes:
      - ./test:/app/test
      - ./package.json:/app/package.json
